modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="MIT License"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="dimstrider" #mandatory
version="0.1.0" #mandatory
displayName="DimStrider" #mandatory
logoFile="examplemod.png" #optional
authors="DantesDoesThings" #optional
description='''
A mod for becoming an all-powerful Dim Strider, an epic wizard of sorts.
'''

[[dependencies.dimstrider]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.dimstrider]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
